### ISSUE TITLE
Logging Middleware

### ISSUE THREAD

**Issue by jakenichols2719** [cloudretic/router#20]
Implement middleware `LogRequests` to write information on incoming requests to an `io.Writer`. You may assume that the end user is defining behavior for the `Writer`.

Implement middleware `LogRequestsByFilters` which can do the same as above, but based on a filter provided by the end user, i.e. `req.Header == http.MethodGet` -> `logGetRequest`.

**Comment by Mihai22125** [comment]
Hi, I'm new to this project and would love to contribute. Can I be assigned to this issue?

**Comment by jakenichols2719** [comment]
Sure thing! I'm assigning you the issue now. Thanks for taking this on!

**Comment by SuneelFreimuth** [comment]
There hasn't been a PR on this issue as of yet, so I'm down to take this up

**Comment by jakenichols2719** [comment]
Resolved after merging #36
