### ISSUE TITLE
Require Queries

### ISSUE THREAD

**Issue by jakenichols2719** [cloudretic/router#23]
Go provides a way to get query parameters, ex. `https://page.com/path?query=value`, but not a way to require them from requests. Implement a `ConfigFunc` for _routes_ that requires certain query parameters to be present in the request.

**Comment by jakenichols2719** [comment]
Additional note: the route should still match, but should respond with `400 Bad Request` and an error message detailing what parameter(s) were missing.

**Comment by SuneelFreimuth** [comment]
I'll take this up.

**Comment by jakenichols2719** [comment]
Assigned! I'll keep an eye out here for questions/clarification.

**Comment by SuneelFreimuth** [comment]
How are `ConfigFunc`s intended to modify a route if they take the route by value instead of by pointer?

**Comment by jakenichols2719** [comment]
@SuneelFreimuth `ConfigFunc` is built to run on `Route` objects, which are interfaces; the concrete routes, like `defaultRoute` or `partialRoute`, are usually pointers, and are just abstracted away in this case. However, the `Route` interface doesn't currently have a way of doing this, which may be where you're running into an issue.

A good starting place may be looking at `Router` to see how it handles the validation of requests through `Attach`ing middleware; you will probably need to define a similar function for `Route`, and implement it in the aforementioned concrete classes.

**Comment by jakenichols2719** [comment]
#31 has been merged. Thanks for the great work!
